// Importing necessary decorators and types from TypeORM and other models
import { Entity, PrimaryGeneratedColumn, Column, OneToMany } from 'typeorm';
import { ShoppingItem } from '../entities/ShoppingItem';  // Importing the ShoppingItem entity to establish a relationship

// Using the @Entity decorator to tell TypeORM that this class is a database entity
@Entity()
export class User {
  // Unique identifier for each user, auto-generated by the database
  @PrimaryGeneratedColumn()
  id!: number;

  // The username of the user, because "User123" is less personal than "LukeTheCoder"
  @Column()
  username!: string;

  // The email of the user, the digital address where they receive all their "You've won $1,000,000" emails
  @Column()
  email!: string;

  // The password, the secret handshake that grants you entry into the user's digital life
  @Column()
  password!: string;

  // New field to establish a One-to-Many relationship with ShoppingItem
  // One user can have multiple shopping items, but each shopping item belongs to one user
  @OneToMany(() => ShoppingItem, (shoppingItem) => shoppingItem!.user)
  shoppingItems!: ShoppingItem[];
}
